name: desafio-assinaturas

services:
  app:
    build:
      context: ./docker/php-fpm/
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: subscriptions
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data

  nginx:
    build:
      context: ./docker/nginx/
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:80"
    depends_on:
      - app