on:
  workflow_run:
    workflows: ["TESTS"]
    types:
      - completed

name: PRODUCTION-DEPLOY

jobs:
  production-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Echo test
        run: |
          echo "hello"