on: push

name: PRODUCTION-DEPLOY

jobs:
  production-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Production
        run: |
          ssh user@your-server "echo 'Deployment successful!'"
