on:
  workflow_run:
    workflows: ["TESTS"]
    types:
      - completed

name: PRODUCTION-DEPLOY

jobs:
  production-deploy:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2

    steps:
      - name: Echo test
        run: |
          echo "hello"
