on: push

name: CI

jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
 
    - name: Install composer dependencies
      run: |
        composer install --no-scripts
 
    # - name: Run Testsuite
    #   run: vendor/bin/phpunit tests/